"""initial_full_schema

Revision ID: a43107475789
Revises: 
Create Date: 2026-03-08 11:07:22.865689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a43107475789'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('exercises', 'create_at')
    op.add_column('users', sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', name='activitylevel'), nullable=True))
    op.drop_column('users', 'activity__level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activity__level', postgresql.ENUM('sedentary', 'light', 'moderate', 'active', name='activitylevel'), autoincrement=False, nullable=True))
    op.drop_column('users', 'activity_level')
    op.add_column('exercises', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('exercises', 'created_at')
    # ### end Alembic commands ###
